# Generated by Django 4.1.3 on 2022-11-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbsqlite", "0004_alter_dbsqlite_age_alter_dbsqlite_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbsqlite",
            name="age",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="email",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="father_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="our_image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="image"
            ),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="password",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
