# Generated by Django 4.1.3 on 2022-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbsqlite", "0005_alter_dbsqlite_age_alter_dbsqlite_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbsqlite",
            name="age",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="email",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="father_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="our_image",
            field=models.ImageField(default="", upload_to="image"),
        ),
        migrations.AlterField(
            model_name="dbsqlite",
            name="password",
            field=models.CharField(default="", max_length=50),
        ),
    ]
