# Generated by Django 4.1.3 on 2022-11-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbsqlite", "0011_alter_dbsqlite_age_alter_dbsqlite_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbsqlite", old_name="name", new_name="my_name",
        ),
    ]
