# Generated by Django 4.1.3 on 2022-11-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbsqlite", "0012_rename_name_dbsqlite_my_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbsqlite", old_name="my_name", new_name="name",
        ),
    ]
