# Generated by Django 4.1.3 on 2022-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbsqlite", "0013_rename_my_name_dbsqlite_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbsqlite",
            name="hello",
            field=models.CharField(default="", max_length=50),
        ),
    ]
