# Generated by Django 4.1.3 on 2022-11-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbsqlite", "0014_dbsqlite_hello"),
    ]

    operations = [
        migrations.RemoveField(model_name="dbsqlite", name="hello",),
    ]
